services:
  caddy-dev:
    image: caddy:2-alpine
    container_name: caddy-ranchbot-webgui-dev
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT_DEV:-8088}:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - php_public_assets_dev:/srv/php-app/public:ro
      - caddy_data_ranchbot_webgui_dev:/data
      - caddy_config_ranchbot_webgui_dev:/config
    networks:
      - ranchbot_webgui_dev_net
    depends_on:
      - php-dev
    environment:
      - EXISTING_RANCHBOT_API_ADDRESS=${EXISTING_RANCHBOT_API_ADDRESS}
      - CADDY_HTTP_PORT_DEV=${CADDY_HTTP_PORT_DEV}
      - ACME_EMAIL=${ACME_EMAIL}
      - YOUR_DOMAIN=${YOUR_DOMAIN}
    env_file:
      - .env.dev

  php-dev:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fpm-ranchbot-webgui-dev
    restart: unless-stopped
    volumes:
      - php_public_assets_dev:/var/www/html/public
      - .:/app
    networks:
      - ranchbot_webgui_dev_net
    env_file:
      - .env.dev

networks:
  ranchbot_webgui_dev_net:
    driver: bridge

volumes:
  caddy_data_ranchbot_webgui_dev:
  caddy_config_ranchbot_webgui_dev:
  php_public_assets_dev:
