version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-ranchbot-webgui
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - php_public_assets:/srv/php-app/public:ro
      - caddy_data_ranchbot_webgui:/data
      - caddy_config_ranchbot_webgui:/config
    networks:
      - ranchbot_webgui_net
    depends_on:
      - php
    environment:
      - YOUR_DOMAIN=${YOUR_DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
      - EXISTING_RANCHBOT_API_ADDRESS=${EXISTING_RANCHBOT_API_ADDRESS}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fpm-ranchbot-webgui
    restart: unless-stopped
    volumes:
      - php_public_assets:/var/www/html/public
      - .:/app
    networks:
      - ranchbot_webgui_net
networks:
  ranchbot_webgui_net:
    driver: bridge

volumes:
  caddy_data_ranchbot_webgui:
  caddy_config_ranchbot_webgui:
  php_public_assets:
