services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ranchbot-backend
    restart: unless-stopped
    environment:
      - RANCHBOT_API_URL=${RANCHBOT_API_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_MAX_AGE=${SESSION_MAX_AGE}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ENABLE_API_DOCS=${ENABLE_API_DOCS:-False}
    volumes:
      - thumbnail-cache:/tmp/thumbnails
      - adjusted-video-cache:/tmp/adjusted_videos
    networks:
      - ranchbot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ranchbot-frontend
    restart: unless-stopped
    ports:
      - '8880:80'
    depends_on:
      - backend
    networks:
      - ranchbot-network

networks:
  ranchbot-network:
    driver: bridge

volumes:
  thumbnail-cache:
  adjusted-video-cache:
