version: '3.8'

services:
  backend:
    image: dam245222/ranchbot-backend:latest
    container_name: ranchbot-backend
    restart: unless-stopped
    environment:
      - RANCHBOT_API_URL=http://192.168.1.210:8077/api/v1
      - SECRET_KEY=change-this-to-your-secret-key
      - SESSION_MAX_AGE=86400
      - ALLOWED_ORIGINS=https://ranchbot.pl,http://localhost:8880
    networks:
      - ranchbot-network

  frontend:
    image: dam245222/ranchbot-frontend:latest
    container_name: ranchbot-frontend
    restart: unless-stopped
    ports:
      - '8880:80'
    depends_on:
      - backend
    networks:
      - ranchbot-network

networks:
  ranchbot-network:
    driver: bridge
