/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#f2a94c',
        'primary-light': '#ffb95c',
        'primary-dark': '#e2993c',
        secondary: '#4CAF50',
        'secondary-light': '#5ee271',
        'secondary-dark': '#45a049',
        'secondary-dark-hover': '#35a33a',
        accent: '#ffb85c',
        'bg-start': '#1aa899',
        'bg-end': '#f2a94c',
        'user-btn': '#f2a94c',
        'user-btn-dark': '#e09340',
        'user-btn-hover': '#ffb85c',
        'auth-btn': '#aaaaaa',
        'auth-btn-dark': '#999999',
        'auth-btn-hover': '#bbbbbb',
        'text-light': '#fff',
        'text-dark': '#0c7730',
        dark: '#333',
        muted: '#666',
        white: '#fff',
        success: '#22aa22',
        warning: '#ffb142',
        error: '#e74c3c',
        info: '#3498db',
        'btn-bg': '#888',
        'btn-bg-hover': '#666',
        'btn-green': '#4CAF50',
        'btn-green-dark': '#45a049',
        'btn-green-hover': '#5ee271',
        'btn-green-hover-dark': '#35a33a',
        'quote-bg': '#fff',
        'quote-text': '#222',
        'title-bg': '#888',
        'form-bg': '#ffe4b5',
        'form-highlight': '#fdda9f',
        'form-focus': '#ffe0a3',
        'form-input': '#fdd99d',
        'form-text': '#8B4513',
        'form-placeholder': '#A0522D',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(to bottom right, #4CAF50, #45a049)',
        'gradient-primary-hover': 'linear-gradient(to bottom right, #5ee271, #35a33a)',
        'gradient-secondary': 'linear-gradient(to right, #ffffff, #d8ffd8)',
        'gradient-secondary-hover': 'linear-gradient(to right, #eaffea, #b0f7b0)',
        'gradient-action': 'linear-gradient(145deg, #f2a94c, #e09340)',
        'gradient-action-hover': 'linear-gradient(145deg, #ffb85c, #f2a94c)',
        'gradient-form-btn': 'linear-gradient(to right, #fdd99d, #dcae75)',
        'gradient-form-btn-hover': 'linear-gradient(to right, #ffe0b3, #e0b88a)',
        'gradient-user-btn': 'linear-gradient(145deg, #f2a94c, #e09340)',
        'gradient-user-btn-hover': 'linear-gradient(145deg, #ffb85c, #f2a94c)',
        'gradient-auth-btn': 'linear-gradient(145deg, #aaaaaa, #999999)',
        'gradient-auth-btn-hover': 'linear-gradient(145deg, #bbbbbb, #aaaaaa)',
      },
      boxShadow: {
        standard: '0 4px 10px rgba(0, 0, 0, 0.1)',
        strong: '0 6px 14px rgba(0, 0, 0, 0.3)',
        active: '0 2px 4px rgba(0, 0, 0, 0.2)',
        hover: '0 8px 16px rgba(0, 0, 0, 0.3)',
        'glow-orange': '0 0 30px rgba(255, 184, 92, 0.8)',
        'input-inset': 'inset 0 0 3px rgba(0, 0, 0, 0.3)',
      },
      borderRadius: {
        's': '8px',
        'm': '10px',
        'l': '20px',
        'xl': '40px',
        'full': '9999px',
      },
      height: {
        '70vh': '70vh',
        '80vh': '80vh',
        '65vh': '65vh',
        '28vh': '28vh',
        '88vh': '88vh',
      },
      maxHeight: {
        '70vh': '70vh',
      },
      width: {
        '70vw': '70vw',
        '90vw': '90vw',
        '500px': '500px',
      },
      maxWidth: {
        '500px': '500px',
        '700px': '700px',
        '800px': '800px',
        '1080px': '1080px',
        '1600px': '1600px',
      },
      spacing: {
        '2.5': '0.625rem',
        '7.5': '1.875rem',
        '15': '3.75rem',
      },
      inset: {
        '7.5': '30px',
      },
      zIndex: {
        '1': '1',
        '5': '5',
        '10': '10',
        '50': '50',
        '100': '100',
        '200': '200',
        '1000': '1000',
      },
      scale: {
        '102': '1.02',
        '105': '1.05',
        '108': '1.08',
        '115': '1.15',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeOut: {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        fadeInScale: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        fadeOutScale: {
          from: { opacity: '1', transform: 'scale(1)' },
          to: { opacity: '0', transform: 'scale(0.95)' },
        },
        pulse: {
          '0%': { opacity: '0.7' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0.7' },
        },
        bounce: {
          '0%, 100%': { transform: 'translateX(0)' },
          '50%': { transform: 'translateX(10px)' },
        },
        bounceVertical: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(10px)' },
        },
        bounceRotated: {
          '0%, 100%': { transform: 'rotate(90deg) translateX(0)' },
          '50%': { transform: 'rotate(90deg) translateX(10px)' },
        },
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        slideInUp: {
          from: { transform: 'translateY(20px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        slideInDown: {
          from: { transform: 'translateY(-20px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        slideInLeft: {
          from: { transform: 'translateX(-20px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          from: { transform: 'translateX(20px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease forwards',
        'fade-out': 'fadeOut 0.3s ease forwards',
        'fade-in-scale': 'fadeInScale 0.5s ease-out forwards',
        'fade-out-scale': 'fadeOutScale 0.5s ease-out forwards',
        'pulse': 'pulse 1.5s infinite',
        'bounce': 'bounce 1.5s infinite',
        'bounce-vertical': 'bounceVertical 1.5s infinite',
        'bounce-rotated': 'bounceRotated 1.5s infinite',
        'spin': 'spin 0.8s linear infinite',
        'spin-slow': 'spin 2s linear infinite',
        'slide-in-up': 'slideInUp 0.5s ease forwards',
        'slide-in-down': 'slideInDown 0.5s ease forwards',
        'slide-in-left': 'slideInLeft 0.5s ease forwards',
        'slide-in-right': 'slideInRight 0.5s ease forwards',
      },
      transitionDuration: {
        '400': '400ms',
      },
    },
  },
  plugins: [],
}
